/* ════════════════════════════════════════════════
   PROFESSIONAL PDF REPORT GENERATOR
   Multi-page consulting-style report
   ════════════════════════════════════════════════ */

async function generateProfessionalReport() {
  if (!state.results) {
    toast('Calculate results before generating report.', 'warning');
    return;
  }

  if (!window.jspdf) {
    toast('PDF library not available.', 'error');
    return;
  }

  const button = document.getElementById('btn-export-pdf');
  setLoading(button, true);
  toast('Generating professional report...', 'info', 2000);

  try {
    const { jsPDF } = window.jspdf;
    const pdf = new jsPDF('p', 'mm', 'a4');
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const margin = 15;
    const contentWidth = pageWidth - (margin * 2);

    // Extract chart images
    const chartImages = await extractChartImages();

    // Page 1: Cover Page
    addCoverPage(pdf, pageWidth, pageHeight);

    // Page 2: Executive Summary
    pdf.addPage();
    addExecutiveSummary(pdf, margin, contentWidth);

    // Page 3: Criteria & Weights
    pdf.addPage();
    addCriteriaWeights(pdf, margin, contentWidth);

    // Page 4: Options & Scores
    pdf.addPage();
    addOptionsScores(pdf, margin, contentWidth);

    // Page 5: Charts
    if (chartImages.bar || chartImages.radar) {
      pdf.addPage();
      addChartsPage(pdf, margin, contentWidth, chartImages);
    }

    // Page 6: Detailed Insights
    if (state.insights) {
      pdf.addPage();
      addDetailedInsights(pdf, margin, contentWidth);
    }

    // Page 7: Sensitivity Analysis (if available)
    if (sensitivityState.active && sensitivityState.original && sensitivityState.current) {
      pdf.addPage();
      addSensitivitySummary(pdf, margin, contentWidth);
    }

    // Page 8: Scenario Simulation (if available)
    if (scenarioState.active && scenarioState.scenarios.length) {
      pdf.addPage();
      addScenarioSummary(pdf, margin, contentWidth);
    }

    // Save PDF
    const safeTitle = (state.decision.title || 'decision-report')
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '');
    
    pdf.save(`${safeTitle}-analysis-report.pdf`);
    toast('Professional report generated successfully!', 'success');
  } catch (error) {
    console.error('PDF generation error:', error);
    toast(`Report generation failed: ${error.message}`, 'error', 5000);
  } finally {
    setLoading(button, false);
  }
}

// ════════════════════════════════════════════════
// PAGE 1: COVER PAGE
// ════════════════════════════════════════════════

function addCoverPage(pdf, pageWidth, pageHeight) {
  const centerX = pageWidth / 2;
  const centerY = pageHeight / 2;

  // Title
  pdf.setFontSize(32);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(30, 30, 30);
  const titleLines = pdf.splitTextToSize(state.decision.title || 'Decision Analysis', pageWidth - 40);
  pdf.text(titleLines, centerX, centerY - 40, { align: 'center' });

  // Subtitle
  pdf.setFontSize(18);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(100, 100, 100);
  pdf.text('Decision Analysis Report', centerX, centerY - 10, { align: 'center' });

  // Date
  pdf.setFontSize(12);
  pdf.setTextColor(120, 120, 120);
  const date = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
  pdf.text(date, centerX, centerY + 10, { align: 'center' });

  // Tagline
  pdf.setFontSize(10);
  pdf.setTextColor(150, 150, 150);
  pdf.text('Generated by Personal Decision Intelligence System', centerX, pageHeight - 20, { align: 'center' });
}

// ════════════════════════════════════════════════
// PAGE 2: EXECUTIVE SUMMARY
// ════════════════════════════════════════════════

function addExecutiveSummary(pdf, margin, contentWidth) {
  let y = margin;

  // Page title
  pdf.setFontSize(20);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(30, 30, 30);
  pdf.text('Executive Summary', margin, y);
  y += 12;

  // Divider
  pdf.setDrawColor(200, 200, 200);
  pdf.setLineWidth(0.5);
  pdf.line(margin, y, margin + contentWidth, y);
  y += 10;

  // Final Recommendation
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(40, 40, 40);
  pdf.text('Final Recommendation', margin, y);
  y += 8;

  const winner = state.results[0];
  pdf.setFontSize(16);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(139, 92, 246);
  pdf.text(`→ ${winner.name}`, margin + 5, y);
  y += 6;

  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(80, 80, 80);
  pdf.text(`Total Score: ${winner.total_score.toFixed(1)} / 100`, margin + 5, y);
  y += 12;

  // Confidence Score
  if (confidenceState.score !== null) {
    pdf.setFontSize(14);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(40, 40, 40);
    pdf.text('Decision Confidence', margin, y);
    y += 8;

    const confidenceColor = confidenceState.color === 'success' ? [34, 197, 94] :
                           confidenceState.color === 'warning' ? [245, 158, 11] : [239, 68, 68];
    
    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(...confidenceColor);
    pdf.text(`${confidenceState.level} (${(confidenceState.score * 100).toFixed(0)}%)`, margin + 5, y);
    y += 6;

    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(80, 80, 80);
    const confidenceText = getConfidenceSummary();
    const confidenceLines = pdf.splitTextToSize(confidenceText, contentWidth - 10);
    pdf.text(confidenceLines, margin + 5, y);
    y += (confidenceLines.length * 5) + 8;
  }

  // Key Insights
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(40, 40, 40);
  pdf.text('Key Insights', margin, y);
  y += 8;

  const keyInsights = generateKeyInsights();
  keyInsights.forEach((insight, idx) => {
    if (y > 260) return; // Prevent overflow
    
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(80, 80, 80);
    pdf.text(`• ${insight}`, margin + 5, y);
    y += 6;
  });
}

// ════════════════════════════════════════════════
// PAGE 3: CRITERIA & WEIGHTS
// ════════════════════════════════════════════════

function addCriteriaWeights(pdf, margin, contentWidth) {
  let y = margin;

  // Page title
  pdf.setFontSize(20);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(30, 30, 30);
  pdf.text('Evaluation Criteria & Weights', margin, y);
  y += 12;

  pdf.setDrawColor(200, 200, 200);
  pdf.setLineWidth(0.5);
  pdf.line(margin, y, margin + contentWidth, y);
  y += 10;

  // Table header
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(60, 60, 60);
  pdf.text('Criterion', margin, y);
  pdf.text('Weight', margin + 120, y);
  pdf.text('Visual', margin + 150, y);
  y += 6;

  pdf.setLineWidth(0.3);
  pdf.line(margin, y, margin + contentWidth, y);
  y += 6;

  // Table rows
  state.decision.criteria.forEach((criterion, idx) => {
    if (y > 270) return; // Prevent overflow

    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(40, 40, 40);
    
    // Criterion name
    const nameText = pdf.splitTextToSize(criterion.name, 110);
    pdf.text(nameText[0], margin, y);
    
    // Weight
    pdf.text(`${criterion.weight.toFixed(1)}%`, margin + 120, y);
    
    // Visual bar
    const barWidth = (criterion.weight / 100) * 30;
    pdf.setFillColor(139, 92, 246);
    pdf.rect(margin + 150, y - 3, barWidth, 4, 'F');
    
    y += 8;
  });
}

// ════════════════════════════════════════════════
// PAGE 4: OPTIONS & SCORES
// ════════════════════════════════════════════════

function addOptionsScores(pdf, margin, contentWidth) {
  let y = margin;

  // Page title
  pdf.setFontSize(20);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(30, 30, 30);
  pdf.text('Options & Scores', margin, y);
  y += 12;

  pdf.setDrawColor(200, 200, 200);
  pdf.setLineWidth(0.5);
  pdf.line(margin, y, margin + contentWidth, y);
  y += 10;

  // Table header
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(60, 60, 60);
  pdf.text('Rank', margin, y);
  pdf.text('Option', margin + 20, y);
  pdf.text('Total Score', margin + 120, y);
  pdf.text('Visual', margin + 155, y);
  y += 6;

  pdf.setLineWidth(0.3);
  pdf.line(margin, y, margin + contentWidth, y);
  y += 6;

  // Table rows
  const maxScore = state.results[0].total_score;
  
  state.results.forEach((result, idx) => {
    if (y > 270) return;

    pdf.setFontSize(10);
    
    // Rank
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(40, 40, 40);
    pdf.text(`#${result.rank}`, margin, y);
    
    // Option name
    pdf.setFont('helvetica', result.rank === 1 ? 'bold' : 'normal');
    if (result.rank === 1) {
      pdf.setTextColor(139, 92, 246);
    } else {
      pdf.setTextColor(40, 40, 40);
    }
    const optionText = pdf.splitTextToSize(result.name, 95);
    pdf.text(optionText[0], margin + 20, y);
    
    // Score
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(40, 40, 40);
    pdf.text(result.total_score.toFixed(1), margin + 120, y);
    
    // Visual bar
    const barWidth = (result.total_score / maxScore) * 25;
    const barColor = result.rank === 1 ? [139, 92, 246] : [148, 163, 184];
    pdf.setFillColor(...barColor);
    pdf.rect(margin + 155, y - 3, barWidth, 4, 'F');
    
    y += 8;
  });
}

// ════════════════════════════════════════════════
// PAGE 5: CHARTS
// ════════════════════════════════════════════════

async function extractChartImages() {
  const images = {};
  
  try {
    if (state.charts.bar) {
      images.bar = state.charts.bar.toBase64Image();
    }
    if (state.charts.radar) {
      images.radar = state.charts.radar.toBase64Image();
    }
  } catch (error) {
    console.error('Chart extraction error:', error);
  }
  
  return images;
}

function addChartsPage(pdf, margin, contentWidth, chartImages) {
  let y = margin;

  // Page title
  pdf.setFontSize(20);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(30, 30, 30);
  pdf.text('Visual Analysis', margin, y);
  y += 12;

  pdf.setDrawColor(200, 200, 200);
  pdf.setLineWidth(0.5);
  pdf.line(margin, y, margin + contentWidth, y);
  y += 10;

  // Bar chart
  if (chartImages.bar) {
    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(60, 60, 60);
    pdf.text('Score Comparison', margin, y);
    y += 8;

    const chartWidth = contentWidth;
    const chartHeight = 80;
    pdf.addImage(chartImages.bar, 'PNG', margin, y, chartWidth, chartHeight);
    y += chartHeight + 10;
  }

  // Radar chart
  if (chartImages.radar && y < 200) {
    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(60, 60, 60);
    pdf.text('Criteria Distribution', margin, y);
    y += 8;

    const chartWidth = contentWidth;
    const chartHeight = 80;
    pdf.addImage(chartImages.radar, 'PNG', margin, y, chartWidth, chartHeight);
  }
}

// ════════════════════════════════════════════════
// PAGE 6: DETAILED INSIGHTS
// ════════════════════════════════════════════════

function addDetailedInsights(pdf, margin, contentWidth) {
  let y = margin;

  // Page title
  pdf.setFontSize(20);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(30, 30, 30);
  pdf.text('Detailed Insights', margin, y);
  y += 12;

  pdf.setDrawColor(200, 200, 200);
  pdf.setLineWidth(0.5);
  pdf.line(margin, y, margin + contentWidth, y);
  y += 10;

  // Explanation
  if (state.insights.explanation) {
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(60, 60, 60);
    const explLines = pdf.splitTextToSize(state.insights.explanation, contentWidth);
    pdf.text(explLines, margin, y);
    y += (explLines.length * 5) + 8;
  }

  // Pros
  if (state.insights.pros?.length) {
    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(34, 197, 94);
    pdf.text('Strengths', margin, y);
    y += 6;

    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(60, 60, 60);
    state.insights.pros.slice(0, 5).forEach(pro => {
      if (y > 270) return;
      const proLines = pdf.splitTextToSize(`• ${pro}`, contentWidth - 5);
      pdf.text(proLines, margin + 3, y);
      y += (proLines.length * 5) + 2;
    });
    y += 6;
  }

  // Cons
  if (state.insights.cons?.length && y < 240) {
    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(239, 68, 68);
    pdf.text('Weaknesses', margin, y);
    y += 6;

    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(60, 60, 60);
    state.insights.cons.slice(0, 5).forEach(con => {
      if (y > 270) return;
      const conLines = pdf.splitTextToSize(`• ${con}`, contentWidth - 5);
      pdf.text(conLines, margin + 3, y);
      y += (conLines.length * 5) + 2;
    });
  }
}

// ════════════════════════════════════════════════
// PAGE 7: SENSITIVITY SUMMARY
// ════════════════════════════════════════════════

function addSensitivitySummary(pdf, margin, contentWidth) {
  let y = margin;

  pdf.setFontSize(20);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(30, 30, 30);
  pdf.text('Sensitivity Analysis', margin, y);
  y += 12;

  pdf.setDrawColor(200, 200, 200);
  pdf.setLineWidth(0.5);
  pdf.line(margin, y, margin + contentWidth, y);
  y += 10;

  const stability = calculateStability();
  
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'bold');
  const stabilityColor = stability.level === 'high' ? [34, 197, 94] :
                        stability.level === 'medium' ? [245, 158, 11] : [239, 68, 68];
  pdf.setTextColor(...stabilityColor);
  pdf.text(`Decision Stability: ${stability.label}`, margin, y);
  y += 8;

  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(60, 60, 60);
  const descLines = pdf.splitTextToSize(stability.description, contentWidth);
  pdf.text(descLines, margin, y);
}

// ════════════════════════════════════════════════
// PAGE 8: SCENARIO SUMMARY
// ════════════════════════════════════════════════

function addScenarioSummary(pdf, margin, contentWidth) {
  let y = margin;

  pdf.setFontSize(20);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(30, 30, 30);
  pdf.text('Scenario Simulation', margin, y);
  y += 12;

  pdf.setDrawColor(200, 200, 200);
  pdf.setLineWidth(0.5);
  pdf.line(margin, y, margin + contentWidth, y);
  y += 10;

  // Table header
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(60, 60, 60);
  pdf.text('Scenario', margin, y);
  pdf.text('Winner', margin + 80, y);
  pdf.text('Score', margin + 140, y);
  y += 6;

  pdf.setLineWidth(0.3);
  pdf.line(margin, y, margin + contentWidth, y);
  y += 6;

  // Base
  const baseWinner = scenarioState.base.results[0];
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(40, 40, 40);
  pdf.text('Base Decision', margin, y);
  pdf.setFont('helvetica', 'normal');
  pdf.text(baseWinner.name, margin + 80, y);
  pdf.text(baseWinner.total_score.toFixed(1), margin + 140, y);
  y += 7;

  // Scenarios
  scenarioState.scenarios.forEach(scenario => {
    if (y > 270) return;
    
    const winner = scenario.results[0];
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(40, 40, 40);
    pdf.text(scenario.name, margin, y);
    pdf.text(winner.name, margin + 80, y);
    pdf.text(winner.total_score.toFixed(1), margin + 140, y);
    y += 7;
  });
}

// ════════════════════════════════════════════════
// HELPER FUNCTIONS
// ════════════════════════════════════════════════

function getConfidenceSummary() {
  if (confidenceState.level === 'High') {
    return 'Excellent decision quality with strong differentiation and balanced evaluation.';
  } else if (confidenceState.level === 'Medium') {
    return 'Reasonable decision quality. Consider validating key assumptions.';
  } else {
    return 'Low confidence. Review criteria, weights, and scores before finalizing.';
  }
}

function generateKeyInsights() {
  const insights = [];
  const winner = state.results[0];
  const runnerUp = state.results[1];

  // Winner insight
  insights.push(`${winner.name} is the recommended choice with a score of ${winner.total_score.toFixed(1)}`);

  // Gap insight
  if (runnerUp) {
    const gap = winner.total_score - runnerUp.total_score;
    if (gap > 15) {
      insights.push(`Clear winner with ${gap.toFixed(1)} point lead over ${runnerUp.name}`);
    } else if (gap < 5) {
      insights.push(`Close competition with ${runnerUp.name} (${gap.toFixed(1)} point gap)`);
    }
  }

  // Criteria insight
  const topCriterion = state.decision.criteria.reduce((max, c) => 
    c.weight > max.weight ? c : max
  );
  insights.push(`Decision heavily weighted by ${topCriterion.name} (${topCriterion.weight.toFixed(1)}%)`);

  // Confidence insight
  if (confidenceState.score !== null) {
    if (confidenceState.level === 'High') {
      insights.push('High confidence - decision is robust and well-supported');
    } else if (confidenceState.level === 'Low') {
      insights.push('Low confidence - consider gathering more data');
    }
  }

  return insights.slice(0, 4);
}

// Replace the old export function
window.exportResultsAsPDF = generateProfessionalReport;
